### ISSUE TITLE
Update OARS data

### ISSUE THREAD

**Issue by cassidyjames** [arshubham/gitignore#5]
Since your app hits an online API, you must update your `social-info` level in your OARS data to be `mild` or higher.

```xml
<content_attribute id="social-info">mild</content_attribute>
```

If more diagnostic data is shared (i.e. more than a ping), it should be moderate or higher:

```xml
<content_attribute id="social-info">moderate</content_attribute>
```

If potentially user-identifiable data (like logs or usernames) are shared, it should be intense:

```xml
<content_attribute id="social-info">intense</content_attribute>
```

**Comment by arshubham** [comment]
Addressed in https://github.com/arshubham/gitignore/commit/be5497158b00f1975f0eee35eea3e065633e314f . Will be released soon.
